web-integration:
  server-port: 8081
  code-timeout: 300 # seconds
  ssl:
    enabled: false
    # path to certificate file, e.g. /path/to/your/fullchain.pem
    cert-path: ""
    # path to private key file, e.g. /path/to/your/privkey.pem (leave empty if bundled with the cert)
    key-path: ""

  registered-clients: []
    # Example client:
    # - name: "My Awesome App"
    #   client-id: "my-client-id"
    #   client-secret: "my-super-secret-client-secret"
    #   redirect-uris:
    #     - "https://my-app.com/callback"
    #   allowed-scopes:
    #     - "profile:nickname"
    #     - "profile:uuid"

oidc:
  # The URL of your server, which will be used as the 'issuer' (iss) in ID tokens.
  # For example: "https://auth.your-server.com"
  issuer_url: "http://127.0.0.1:8081"
  # Path to the private key file. If left empty, the key will be generated automatically.
  # The path is relative to the plugin's data folder.
  private_key_path: "private.key"
